const NAMES_META = {
  source: "Names, Arabic script, and transliteration cross-checked against the AlAdhan API and standard Asma-ul-Husna references. Core hadith: the enumeration of 99 Names is recorded in Jami at-Tirmidhi 3507 and Sunan Ibn Majah 3861; the promise of Paradise for those who know them is in Sahih al-Bukhari 2736 and Sahih Muslim 2677. Some scholars note the specific ordered enumeration is a later addition to the hadith rather than the Prophet's exact wording, though the 99 Names themselves are firmly rooted in the Qur'an and Sunnah. Qur'an references given per-name are limited to associations that are well-established and widely documented; where no specific verse is cited, the name is affirmed through the broader Qur'anic and prophetic tradition rather than one exact verse.",
  generalRefs: ["Surah Al-A'raf 7:180", "Surah Ta-Ha 20:8", "Surah Al-Hashr 59:22-24"]
};

const NAMES_DATA = [
  {
    "id": 1,
    "ar": "الرَّحْمَنُ",
    "translit": "Ar-Rahman",
    "meaning": "The Most Compassionate",
    "category": "Mercy",
    "short": "The Most Compassionate.",
    "deep": "Allah's mercy is vast enough to embrace every creature, believer and non-believer alike, sustaining all of creation moment to moment.",
    "ref": "Surah Al-Fatihah 1:3; Surah Ar-Rahman 55:1",
    "reflection": "Where in your life have you received mercy you didn't earn?",
    "action": "Show mercy to someone who hasn't earned it from you today."
  },
  {
    "id": 2,
    "ar": "الرَّحِيمُ",
    "translit": "Ar-Rahim",
    "meaning": "The Most Merciful",
    "category": "Mercy",
    "short": "The Most Merciful.",
    "deep": "Where Ar-Rahman is Allah's mercy toward all creation in this life, Ar-Rahim is His special, lasting mercy reserved for the believers.",
    "ref": "Surah Al-Fatihah 1:3",
    "reflection": "How can your mercy today be steady, not just occasional?",
    "action": "Make dua for someone else before asking for yourself."
  },
  {
    "id": 3,
    "ar": "الْمَلِكُ",
    "translit": "Al-Malik",
    "meaning": "The King / Sovereign",
    "category": "Majesty",
    "short": "The King / Sovereign.",
    "deep": "Allah is the true King who owns and governs all dominion, needing nothing and no one, unlike any worldly ruler whose authority is borrowed and temporary.",
    "ref": "Surah Al-Hashr 59:23",
    "reflection": "What are you trying to control that isn't truly yours to own?",
    "action": "Release control of one thing you don't actually own today."
  },
  {
    "id": 4,
    "ar": "الْقُدُّوسُ",
    "translit": "Al-Quddus",
    "meaning": "The Most Holy / Pure",
    "category": "Majesty",
    "short": "The Most Holy / Pure.",
    "deep": "Allah is free of every flaw, defect, and imperfection, utterly pure in His essence, attributes, and actions.",
    "ref": "Surah Al-Hashr 59:23",
    "reflection": "What habit or thought could you hold to a higher, purer standard today?",
    "action": "Do one thing today with more sincerity than usual."
  },
  {
    "id": 5,
    "ar": "السَّلَامُ",
    "translit": "As-Salam",
    "meaning": "The Source of Peace",
    "category": "Protection",
    "short": "The Source of Peace.",
    "deep": "Allah is the source from which all true safety and peace flow, and the name Muslims will hear as their greeting in Paradise.",
    "ref": "Surah Al-Hashr 59:23",
    "reflection": "Where do you need to make peace, with others or with yourself?",
    "action": "Make peace with someone you've been distant from."
  },
  {
    "id": 6,
    "ar": "الْمُؤْمِنُ",
    "translit": "Al-Mu'min",
    "meaning": "The Giver of Faith and Security",
    "category": "Protection",
    "short": "The Giver of Faith and Security.",
    "deep": "Allah inspires faith and certainty in the hearts of believers and grants them security, just as He testifies to the truth of His own promises.",
    "ref": "Surah Al-Hashr 59:23",
    "reflection": "Whose trust can you protect today by keeping your word?",
    "action": "Keep a promise, even a small one, exactly as you made it."
  },
  {
    "id": 7,
    "ar": "الْمُهَيْمِنُ",
    "translit": "Al-Muhaymin",
    "meaning": "The Guardian, the Overseer",
    "category": "Protection",
    "short": "The Guardian, the Overseer.",
    "deep": "Allah watches over, protects, and maintains everything in existence, aware of every hidden and open matter.",
    "ref": "Surah Al-Hashr 59:23",
    "reflection": "How does it feel to know you are always watched over, not just watched?",
    "action": "Do one good deed privately, for no one's eyes but His."
  },
  {
    "id": 8,
    "ar": "الْعَزِيزُ",
    "translit": "Al-Aziz",
    "meaning": "The Almighty, the Mighty",
    "category": "Power",
    "short": "The Almighty, the Mighty.",
    "deep": "Allah's might is complete and unshakable; nothing can overpower Him, and true honour belongs to Him alone.",
    "ref": "Surah Al-Hashr 59:23",
    "reflection": "Where do you need quiet strength instead of loud force?",
    "action": "Choose quiet composure over a loud reaction today."
  },
  {
    "id": 9,
    "ar": "الْجَبَّارُ",
    "translit": "Al-Jabbar",
    "meaning": "The Compeller, the Restorer",
    "category": "Power",
    "short": "The Compeller, the Restorer.",
    "deep": "Allah is the One who compels and restores by His will, mending what is broken in creation and enforcing His decree without resistance.",
    "ref": "Surah Al-Hashr 59:23",
    "reflection": "What situation in your life needs firm, decisive correction?",
    "action": "Correct one bad habit firmly today rather than tomorrow."
  },
  {
    "id": 10,
    "ar": "الْمُتَكَبِّرُ",
    "translit": "Al-Mutakabbir",
    "meaning": "The Supreme in Greatness",
    "category": "Majesty",
    "short": "The Supreme in Greatness.",
    "deep": "Allah alone deserves greatness and pride; arrogance, which is a flaw in any creation, befits no one but Him in its perfect form.",
    "ref": "Surah Al-Hashr 59:23",
    "reflection": "Where has pride crept in that you can humble before Allah?",
    "action": "Say a compliment to someone without needing credit back."
  },
  {
    "id": 11,
    "ar": "الْخَالِقُ",
    "translit": "Al-Khaliq",
    "meaning": "The Creator",
    "category": "Creation",
    "short": "The Creator.",
    "deep": "Allah brings everything into existence from nothing, designing every atom of creation with purpose and precision.",
    "ref": "Surah Al-Hashr 59:24",
    "reflection": "Look at something ordinary and consider it was deliberately designed.",
    "action": "Notice one detail in nature and thank Allah for it."
  },
  {
    "id": 12,
    "ar": "الْبَارِئُ",
    "translit": "Al-Bari",
    "meaning": "The Evolver, the Maker",
    "category": "Creation",
    "short": "The Evolver, the Maker.",
    "deep": "Allah brought creation into being free of any flaw or defect, giving each thing its proper place and order.",
    "ref": "Surah Al-Hashr 59:24",
    "reflection": "What in your life is out of order that could use a fresh start?",
    "action": "Fix or tidy one thing that's been left disordered."
  },
  {
    "id": 13,
    "ar": "الْمُصَوِّرُ",
    "translit": "Al-Musawwir",
    "meaning": "The Fashioner of Forms",
    "category": "Creation",
    "short": "The Fashioner of Forms.",
    "deep": "Allah gives every created thing its unique shape, features, and form, no two exactly alike.",
    "ref": "Surah Al-Hashr 59:24",
    "reflection": "What makes you, specifically you? Reflect on that design.",
    "action": "Thank Allah specifically for a feature of your own design."
  },
  {
    "id": 14,
    "ar": "الْغَفَّارُ",
    "translit": "Al-Ghaffar",
    "meaning": "The Repeatedly Forgiving",
    "category": "Forgiveness",
    "short": "The Repeatedly Forgiving.",
    "deep": "Allah forgives sins again and again, however many times a servant returns to Him in sincere repentance.",
    "ref": null,
    "reflection": "What have you been avoiding asking forgiveness for?",
    "action": "Ask forgiveness for something specific, not just in general."
  },
  {
    "id": 15,
    "ar": "الْقَهَّارُ",
    "translit": "Al-Qahhar",
    "meaning": "The Subduer, the Ever-Dominating",
    "category": "Power",
    "short": "The Subduer, the Ever-Dominating.",
    "deep": "Allah has complete power over all things and subdues every force, tyrant, and obstacle by His will.",
    "ref": null,
    "reflection": "What within you needs to be brought under control?",
    "action": "Resist one small temptation deliberately today."
  },
  {
    "id": 16,
    "ar": "الْوَهَّابُ",
    "translit": "Al-Wahhab",
    "meaning": "The Bestower, the Giver of Gifts",
    "category": "Sustenance",
    "short": "The Bestower, the Giver of Gifts.",
    "deep": "Allah gives generously and repeatedly without any expectation of return, granting gifts to whoever He wills.",
    "ref": null,
    "reflection": "What have you been given freely that you didn't ask for?",
    "action": "Give something away without expecting anything in return."
  },
  {
    "id": 17,
    "ar": "الرَّزَّاقُ",
    "translit": "Ar-Razzaq",
    "meaning": "The Provider, the Sustainer",
    "category": "Sustenance",
    "short": "The Provider, the Sustainer.",
    "deep": "Allah provides sustenance for every living creature, seen and unseen, guaranteeing provision for all He has created.",
    "ref": null,
    "reflection": "Where are you anxious about provision that you could hand over in trust?",
    "action": "Spend without fear on something halal and needed."
  },
  {
    "id": 18,
    "ar": "الْفَتَّاحُ",
    "translit": "Al-Fattah",
    "meaning": "The Opener, the Judge",
    "category": "Guidance",
    "short": "The Opener, the Judge.",
    "deep": "Allah opens what is closed — provision, guidance, hearts, and judgment — and is the ultimate Judge between right and wrong.",
    "ref": null,
    "reflection": "What door feels closed to you right now that you could ask to be opened?",
    "action": "Ask Allah directly to open a specific door for you."
  },
  {
    "id": 19,
    "ar": "اَلْعَلِيْمُ",
    "translit": "Al-Alim",
    "meaning": "The All-Knowing",
    "category": "Knowledge",
    "short": "The All-Knowing.",
    "deep": "Allah's knowledge encompasses everything that was, is, and will be, the seen and the unseen, without limit.",
    "ref": "Surah Al-Baqarah 2:29 (mentioned frequently throughout the Qur'an)",
    "reflection": "What do you assume no one knows about you?",
    "action": "Be honest about something you'd rather hide."
  },
  {
    "id": 20,
    "ar": "الْقَابِضُ",
    "translit": "Al-Qabid",
    "meaning": "The Withholder, the Constrictor",
    "category": "Power",
    "short": "The Withholder, the Constrictor.",
    "deep": "Allah withholds provision, ease, or blessing from whoever He wills, by perfect wisdom rather than randomness.",
    "ref": null,
    "reflection": "What season of constriction are you in, and what might it be teaching you?",
    "action": "Accept a moment of hardship without complaint today."
  },
  {
    "id": 21,
    "ar": "الْبَاسِطُ",
    "translit": "Al-Basit",
    "meaning": "The Extender, the Enlarger",
    "category": "Sustenance",
    "short": "The Extender, the Enlarger.",
    "deep": "Allah extends and expands provision, mercy, and ease to whoever He wills, opening what was once tight.",
    "ref": null,
    "reflection": "Where has ease come to you unexpectedly lately?",
    "action": "Say Alhamdulillah for one unexpected ease today."
  },
  {
    "id": 22,
    "ar": "الْخَافِضُ",
    "translit": "Al-Khafid",
    "meaning": "The Abaser",
    "category": "Justice",
    "short": "The Abaser.",
    "deep": "Allah lowers whoever He wills in rank, status, or circumstance, according to His justice and wisdom.",
    "ref": null,
    "reflection": "Where might humility serve you better than status?",
    "action": "Practice humility in one interaction today."
  },
  {
    "id": 23,
    "ar": "الرَّافِعُ",
    "translit": "Ar-Rafi",
    "meaning": "The Exalter, the Elevator",
    "category": "Majesty",
    "short": "The Exalter, the Elevator.",
    "deep": "Allah raises whoever He wills in rank, honour, or station, elevating the sincere and the humble.",
    "ref": null,
    "reflection": "What would it look like to be raised in character, not just position?",
    "action": "Encourage someone whose position feels lower today."
  },
  {
    "id": 24,
    "ar": "الْمُعِزُّ",
    "translit": "Al-Mu'izz",
    "meaning": "The Bestower of Honour",
    "category": "Majesty",
    "short": "The Bestower of Honour.",
    "deep": "Allah grants honour and dignity to whoever He wills, and no one can honour a person that Allah has not.",
    "ref": null,
    "reflection": "Where are you seeking honour from people when only Allah can truly grant it?",
    "action": "Give credit to Allah, not yourself, for one success."
  },
  {
    "id": 25,
    "ar": "المُذِلُّ",
    "translit": "Al-Muzill",
    "meaning": "The Humiliator, the Dishonourer",
    "category": "Justice",
    "short": "The Humiliator, the Dishonourer.",
    "deep": "Allah can remove honour and bring disgrace upon whoever He wills, regardless of worldly status or power.",
    "ref": null,
    "reflection": "Where has arrogance quietly cost someone their dignity?",
    "action": "Avoid one boastful comment today."
  },
  {
    "id": 26,
    "ar": "السَّمِيعُ",
    "translit": "As-Sami",
    "meaning": "The All-Hearing",
    "category": "Knowledge",
    "short": "The All-Hearing.",
    "deep": "Allah hears every sound, spoken or silent, near or far, including the quietest of prayers.",
    "ref": "Surah Al-Baqarah 2:127",
    "reflection": "Have you noticed how many quiet duas go unspoken but not unheard?",
    "action": "Make one sincere, specific dua out loud or silently."
  },
  {
    "id": 27,
    "ar": "الْبَصِيرُ",
    "translit": "Al-Basir",
    "meaning": "The All-Seeing",
    "category": "Knowledge",
    "short": "The All-Seeing.",
    "deep": "Allah sees everything, in complete darkness or open light, with perfect and total awareness.",
    "ref": "Surah An-Nisa 4:58",
    "reflection": "What do you do differently when you remember you are truly seen?",
    "action": "Do one action as if you can see it being watched."
  },
  {
    "id": 28,
    "ar": "الْحَكَمُ",
    "translit": "Al-Hakam",
    "meaning": "The Judge, the Arbitrator",
    "category": "Justice",
    "short": "The Judge, the Arbitrator.",
    "deep": "Allah is the ultimate Judge whose rulings are final, arbitrating with perfect fairness between all creation.",
    "ref": null,
    "reflection": "Where in your life do you need a fair, final word?",
    "action": "Resolve one small dispute fairly today."
  },
  {
    "id": 29,
    "ar": "الْعَدْلُ",
    "translit": "Al-Adl",
    "meaning": "The Utterly Just",
    "category": "Justice",
    "short": "The Utterly Just.",
    "deep": "Allah is perfectly just in every decree, incapable of wronging anyone even by the smallest measure.",
    "ref": null,
    "reflection": "Where could you be fairer today, even when it costs you?",
    "action": "Give someone their full due today, even if inconvenient."
  },
  {
    "id": 30,
    "ar": "اللَّطِيفُ",
    "translit": "Al-Latif",
    "meaning": "The Subtle, the Gentle One",
    "category": "Love",
    "short": "The Subtle, the Gentle One.",
    "deep": "Allah is subtle and gentle in how He reaches His servants, aware of the finest details others overlook, and kind in how He deals with them.",
    "ref": "Surah Al-An'am 6:103",
    "reflection": "Where do you need gentleness rather than a heavy hand today?",
    "action": "Be gentle in one conversation that could have been harsh."
  },
  {
    "id": 31,
    "ar": "الْخَبِيرُ",
    "translit": "Al-Khabir",
    "meaning": "The All-Aware",
    "category": "Knowledge",
    "short": "The All-Aware.",
    "deep": "Allah is aware of the most hidden realities, intentions, and secrets, missing nothing however concealed.",
    "ref": "Surah Al-An'am 6:103",
    "reflection": "What is hidden in your heart that still shapes how you're treated?",
    "action": "Be honest about a hidden intention, even to yourself."
  },
  {
    "id": 32,
    "ar": "الْحَلِيمُ",
    "translit": "Al-Halim",
    "meaning": "The Forbearing, the Clement",
    "category": "Patience",
    "short": "The Forbearing, the Clement.",
    "deep": "Allah is forbearing with His servants, delaying punishment despite their sins, giving room for repentance.",
    "ref": null,
    "reflection": "Who tested your patience today, and how did you respond?",
    "action": "Delay a reaction by ten seconds before responding today."
  },
  {
    "id": 33,
    "ar": "الْعَظِيمُ",
    "translit": "Al-Azim",
    "meaning": "The Magnificent, the Supreme",
    "category": "Majesty",
    "short": "The Magnificent, the Supreme.",
    "deep": "Allah's greatness surpasses all understanding; nothing in creation compares to His magnificence.",
    "ref": null,
    "reflection": "What problem feels enormous to you, and how does it look next to this attribute?",
    "action": "Recite one dhikr remembering His greatness before a hard task."
  },
  {
    "id": 34,
    "ar": "الْغَفُورُ",
    "translit": "Al-Ghafur",
    "meaning": "The All-Forgiving",
    "category": "Forgiveness",
    "short": "The All-Forgiving.",
    "deep": "Allah forgives abundantly and repeatedly, covering the sins of those who turn back to Him.",
    "ref": "Surah Al-Baqarah 2:173 (mentioned frequently throughout the Qur'an)",
    "reflection": "What is a mistake you keep replaying that could finally be released?",
    "action": "Let go of one old mistake you keep punishing yourself for."
  },
  {
    "id": 35,
    "ar": "الشَّكُورُ",
    "translit": "Ash-Shakur",
    "meaning": "The Most Appreciative",
    "category": "Love",
    "short": "The Most Appreciative.",
    "deep": "Allah rewards even small acts of gratitude and obedience with abundant and lasting reward.",
    "ref": null,
    "reflection": "What small good deed of yours might matter more than you think?",
    "action": "Do one small good deed and trust it's seen."
  },
  {
    "id": 36,
    "ar": "الْعَلِيُّ",
    "translit": "Al-Ali",
    "meaning": "The Most High",
    "category": "Majesty",
    "short": "The Most High.",
    "deep": "Allah is elevated above all creation in status, power, and every possible comparison.",
    "ref": null,
    "reflection": "What are you placing above your relationship with Allah?",
    "action": "Put one worldly priority beneath your prayer today."
  },
  {
    "id": 37,
    "ar": "الْكَبِيرُ",
    "translit": "Al-Kabir",
    "meaning": "The Most Great",
    "category": "Majesty",
    "short": "The Most Great.",
    "deep": "Allah's greatness is absolute and beyond any measure creation could apply to Him.",
    "ref": null,
    "reflection": "What measure of 'great' are you using, and is it the right one?",
    "action": "Reconsider one thing you've called 'too small to matter'."
  },
  {
    "id": 38,
    "ar": "الْحَفِيظُ",
    "translit": "Al-Hafiz",
    "meaning": "The Preserver, the Guardian",
    "category": "Protection",
    "short": "The Preserver, the Guardian.",
    "deep": "Allah protects and preserves His creation, their deeds, and their provision, without ever forgetting.",
    "ref": null,
    "reflection": "What have you been protecting that you could instead entrust?",
    "action": "Entrust one worry to Allah instead of over-controlling it."
  },
  {
    "id": 39,
    "ar": "المُقِيتُ",
    "translit": "Al-Muqit",
    "meaning": "The Sustainer, the Nourisher",
    "category": "Sustenance",
    "short": "The Sustainer, the Nourisher.",
    "deep": "Allah nourishes and sustains every creature's needs, physical and spiritual, without failing.",
    "ref": null,
    "reflection": "What sustains you today that you take for granted?",
    "action": "Share a meal or resource with someone today."
  },
  {
    "id": 40,
    "ar": "الْحسِيبُ",
    "translit": "Al-Hasib",
    "meaning": "The Reckoner",
    "category": "Justice",
    "short": "The Reckoner.",
    "deep": "Allah keeps perfect account of every deed, however small, and will settle it with complete accuracy.",
    "ref": null,
    "reflection": "What are you accountable for that you haven't reckoned with yet?",
    "action": "Review one action honestly before the day ends."
  },
  {
    "id": 41,
    "ar": "الْجَلِيلُ",
    "translit": "Al-Jalil",
    "meaning": "The Majestic",
    "category": "Majesty",
    "short": "The Majestic.",
    "deep": "Allah possesses majesty and greatness that commands awe and reverence from all creation.",
    "ref": null,
    "reflection": "Where do you need reverence instead of casualness?",
    "action": "Sit in stillness for a moment reflecting on His majesty."
  },
  {
    "id": 42,
    "ar": "الْكَرِيمُ",
    "translit": "Al-Karim",
    "meaning": "The Most Generous",
    "category": "Beauty",
    "short": "The Most Generous.",
    "deep": "Allah is generous beyond measure, giving abundantly without being asked and without expecting return.",
    "ref": null,
    "reflection": "Who could you be generous toward today without expecting return?",
    "action": "Be generous with your time to someone today."
  },
  {
    "id": 43,
    "ar": "الرَّقِيبُ",
    "translit": "Ar-Raqib",
    "meaning": "The Watchful",
    "category": "Protection",
    "short": "The Watchful.",
    "deep": "Allah watches over every action and intention constantly, never distracted or unaware.",
    "ref": null,
    "reflection": "What would you do differently if you paused to notice you're being watched?",
    "action": "Do one act of good exactly as you would if watched."
  },
  {
    "id": 44,
    "ar": "الْمُجِيبُ",
    "translit": "Al-Mujib",
    "meaning": "The Responsive, the Answerer",
    "category": "Love",
    "short": "The Responsive, the Answerer.",
    "deep": "Allah answers the call of whoever sincerely turns to Him, in the way and time He knows is best.",
    "ref": null,
    "reflection": "What request have you stopped making because you gave up hope?",
    "action": "Make one specific dua and note the date you asked."
  },
  {
    "id": 45,
    "ar": "الْوَاسِعُ",
    "translit": "Al-Wasi",
    "meaning": "The All-Encompassing",
    "category": "Knowledge",
    "short": "The All-Encompassing.",
    "deep": "Allah's knowledge, mercy, and provision encompass everything, with no limit to what He can give or know.",
    "ref": null,
    "reflection": "What problem feels too big, that isn't too big at all?",
    "action": "Bring one worry to Allah that feels too big to hold."
  },
  {
    "id": 46,
    "ar": "الْحَكِيمُ",
    "translit": "Al-Hakim",
    "meaning": "The All-Wise",
    "category": "Knowledge",
    "short": "The All-Wise.",
    "deep": "Allah's wisdom governs every decree perfectly; nothing He ordains is without purpose or benefit.",
    "ref": "Surah Luqman 31:27 (mentioned frequently throughout the Qur'an)",
    "reflection": "Where do you need wisdom rather than just information?",
    "action": "Ask for wisdom before making one decision today."
  },
  {
    "id": 47,
    "ar": "الْوَدُودُ",
    "translit": "Al-Wadud",
    "meaning": "The Most Loving",
    "category": "Love",
    "short": "The Most Loving.",
    "deep": "Allah loves His righteous servants and is beloved by those who truly know Him.",
    "ref": "Surah Hud 11:90; Surah Al-Buruj 85:14",
    "reflection": "Who is hard to love right now, and what would love ask of you?",
    "action": "Do one loving act for someone you find difficult."
  },
  {
    "id": 48,
    "ar": "الْمَجِيدُ",
    "translit": "Al-Majid",
    "meaning": "The Most Glorious",
    "category": "Majesty",
    "short": "The Most Glorious.",
    "deep": "Allah is glorious in His attributes and generous in His gifts, deserving of praise in every regard.",
    "ref": null,
    "reflection": "What in your life deserves more honour and less complaint?",
    "action": "Speak of Allah's greatness instead of your own achievements today."
  },
  {
    "id": 49,
    "ar": "الْبَاعِثُ",
    "translit": "Al-Ba'ith",
    "meaning": "The Resurrector",
    "category": "Power",
    "short": "The Resurrector.",
    "deep": "Allah will resurrect all of creation for judgment, and He raised Prophets to guide humanity in their time.",
    "ref": null,
    "reflection": "What part of you needs to be revived after feeling dead inside?",
    "action": "Revive one good habit you let go dormant."
  },
  {
    "id": 50,
    "ar": "الشَّهِيدُ",
    "translit": "Ash-Shahid",
    "meaning": "The Witness",
    "category": "Knowledge",
    "short": "The Witness.",
    "deep": "Allah witnesses everything that occurs, testifying to truth even when no one else observes it.",
    "ref": null,
    "reflection": "What would change if you spoke knowing your words are witnessed?",
    "action": "Speak one sentence today as if it's fully witnessed."
  },
  {
    "id": 51,
    "ar": "الْحَقُّ",
    "translit": "Al-Haqq",
    "meaning": "The Absolute Truth",
    "category": "Majesty",
    "short": "The Absolute Truth.",
    "deep": "Allah is the ultimate and only true Reality; everything else exists only through Him and returns to Him.",
    "ref": null,
    "reflection": "Where are you avoiding an uncomfortable truth?",
    "action": "Face one truth you've been avoiding."
  },
  {
    "id": 52,
    "ar": "الْوَكِيلُ",
    "translit": "Al-Wakil",
    "meaning": "The Trustee, the Disposer of Affairs",
    "category": "Protection",
    "short": "The Trustee, the Disposer of Affairs.",
    "deep": "Allah is the One relied upon to manage every affair; those who trust Him find Him sufficient.",
    "ref": null,
    "reflection": "What are you carrying that you could finally hand over?",
    "action": "Hand over one outcome to Allah after doing your part."
  },
  {
    "id": 53,
    "ar": "الْقَوِيُّ",
    "translit": "Al-Qawiyy",
    "meaning": "The All-Strong",
    "category": "Power",
    "short": "The All-Strong.",
    "deep": "Allah possesses complete strength, unmatched by any power in creation.",
    "ref": null,
    "reflection": "Where do you need strength that isn't your own?",
    "action": "Ask Allah for strength before one hard task today."
  },
  {
    "id": 54,
    "ar": "الْمَتِينُ",
    "translit": "Al-Matin",
    "meaning": "The Firm, the Steadfast",
    "category": "Power",
    "short": "The Firm, the Steadfast.",
    "deep": "Allah's strength is unshakeable and forceful, never weakened, and never in need of support.",
    "ref": null,
    "reflection": "What feels shaky right now that needs a firmer foundation?",
    "action": "Stand firm on one principle today despite pressure."
  },
  {
    "id": 55,
    "ar": "الْوَلِيُّ",
    "translit": "Al-Wali",
    "meaning": "The Protecting Friend",
    "category": "Protection",
    "short": "The Protecting Friend.",
    "deep": "Allah is the true protecting friend and helper of the believers, guarding them from harm.",
    "ref": null,
    "reflection": "Who or what are you truly relying on for protection?",
    "action": "Turn to Allah first the next time you feel unsafe."
  },
  {
    "id": 56,
    "ar": "الْحَمِيدُ",
    "translit": "Al-Hamid",
    "meaning": "The Praiseworthy",
    "category": "Beauty",
    "short": "The Praiseworthy.",
    "deep": "Allah is deserving of all praise in every state, whether in ease or hardship.",
    "ref": null,
    "reflection": "What are you praising today, and does it deserve first place?",
    "action": "Praise Allah specifically before praising anything else today."
  },
  {
    "id": 57,
    "ar": "الْمُحْصِي",
    "translit": "Al-Muhsi",
    "meaning": "The Accounter, the Enumerator",
    "category": "Knowledge",
    "short": "The Accounter, the Enumerator.",
    "deep": "Allah keeps a precise count of every action, word, and moment of every creation.",
    "ref": null,
    "reflection": "What have you done that only Allah has kept perfect count of?",
    "action": "Do one good deed without mentioning it to anyone."
  },
  {
    "id": 58,
    "ar": "الْمُبْدِئُ",
    "translit": "Al-Mubdi",
    "meaning": "The Originator",
    "category": "Creation",
    "short": "The Originator.",
    "deep": "Allah originates creation from nothing, initiating existence with no prior model to follow.",
    "ref": null,
    "reflection": "What could you begin again from nothing today?",
    "action": "Start one thing fresh today instead of waiting for perfect conditions."
  },
  {
    "id": 59,
    "ar": "الْمُعِيدُ",
    "translit": "Al-Mu'id",
    "meaning": "The Restorer, the Reproducer",
    "category": "Creation",
    "short": "The Restorer, the Reproducer.",
    "deep": "Allah will restore and resurrect creation after death, just as He originated it the first time.",
    "ref": null,
    "reflection": "What in your life needs restoring rather than replacing?",
    "action": "Repair one relationship or habit instead of abandoning it."
  },
  {
    "id": 60,
    "ar": "الْمُحْيِي",
    "translit": "Al-Muhyi",
    "meaning": "The Giver of Life",
    "category": "Creation",
    "short": "The Giver of Life.",
    "deep": "Allah gives life to the lifeless, both physically at creation and spiritually through faith.",
    "ref": null,
    "reflection": "What feels lifeless in you that could be revived?",
    "action": "Revive one part of your worship that has gone quiet."
  },
  {
    "id": 61,
    "ar": "اَلْمُمِيتُ",
    "translit": "Al-Mumit",
    "meaning": "The Bringer of Death",
    "category": "Justice",
    "short": "The Bringer of Death.",
    "deep": "Allah brings about the death of every living being at its appointed time, by His decree alone.",
    "ref": null,
    "reflection": "How does remembering death change what you do today?",
    "action": "Reflect for a moment on mortality before a decision today."
  },
  {
    "id": 62,
    "ar": "الْحَيُّ",
    "translit": "Al-Hayy",
    "meaning": "The Ever-Living",
    "category": "Majesty",
    "short": "The Ever-Living.",
    "deep": "Allah's life is eternal and complete, without beginning, end, or any need to sustain Himself.",
    "ref": "Surah Al-Baqarah 2:255 (Ayat al-Kursi)",
    "reflection": "What are you relying on that could end, compared to what cannot?",
    "action": "Depend on Allah, not circumstance, for one need today."
  },
  {
    "id": 63,
    "ar": "الْقَيُّومُ",
    "translit": "Al-Qayyum",
    "meaning": "The Self-Subsisting Sustainer",
    "category": "Majesty",
    "short": "The Self-Subsisting Sustainer.",
    "deep": "Allah sustains and maintains all of existence, and nothing in creation continues without Him.",
    "ref": "Surah Al-Baqarah 2:255 (Ayat al-Kursi)",
    "reflection": "What in your life depends entirely on you being sustained?",
    "action": "Notice one thing that depends entirely on being sustained moment to moment."
  },
  {
    "id": 64,
    "ar": "الْوَاجِدُ",
    "translit": "Al-Wajid",
    "meaning": "The Perceiver, the Finder",
    "category": "Knowledge",
    "short": "The Perceiver, the Finder.",
    "deep": "Allah finds and perceives everything He seeks; nothing is ever truly lost from His knowledge.",
    "ref": null,
    "reflection": "What have you been searching for that was closer than you thought?",
    "action": "Search sincerely for something you've been missing through dua."
  },
  {
    "id": 65,
    "ar": "الْمَاجِدُ",
    "translit": "Al-Majid",
    "meaning": "The Glorious, the Noble",
    "category": "Majesty",
    "short": "The Glorious, the Noble.",
    "deep": "Allah is glorious and noble in every attribute, deserving of honour beyond any creation.",
    "ref": null,
    "reflection": "Where do you seek glory in ways that won't last?",
    "action": "Seek one form of honour only from Allah today."
  },
  {
    "id": 66,
    "ar": "الْواحِدُ",
    "translit": "Al-Wahid",
    "meaning": "The Only One",
    "category": "Majesty",
    "short": "The Only One.",
    "deep": "Allah is singularly One in His essence, attributes, and actions, without partner or equal.",
    "ref": "Surah Al-Baqarah 2:163",
    "reflection": "Where do you divide your loyalty that should belong to One alone?",
    "action": "Redirect one loyalty back toward Allah alone."
  },
  {
    "id": 67,
    "ar": "اَلاَحَدُ",
    "translit": "Al-Ahad",
    "meaning": "The One, the Indivisible",
    "category": "Majesty",
    "short": "The One, the Indivisible.",
    "deep": "Allah is the One, indivisible and unique, unlike anything that can be imagined or compared.",
    "ref": "Surah Al-Ikhlas 112:1",
    "reflection": "What comparisons are you making that don't really apply?",
    "action": "Avoid comparing Allah to anything today, even in thought."
  },
  {
    "id": 68,
    "ar": "الصَّمَدُ",
    "translit": "As-Samad",
    "meaning": "The Eternal, Uncaused Refuge",
    "category": "Majesty",
    "short": "The Eternal, Uncaused Refuge.",
    "deep": "Allah is the eternal refuge that all creation depends upon, while He depends on nothing.",
    "ref": "Surah Al-Ikhlas 112:2",
    "reflection": "Who do you turn to first when you're in need?",
    "action": "Turn to Allah first with one need before anyone else."
  },
  {
    "id": 69,
    "ar": "الْقَادِرُ",
    "translit": "Al-Qadir",
    "meaning": "The All-Powerful",
    "category": "Power",
    "short": "The All-Powerful.",
    "deep": "Allah has full power over all things, able to bring about whatever He wills without hindrance.",
    "ref": null,
    "reflection": "What limitation are you treating as final, that isn't?",
    "action": "Ask Allah for ability in one area you feel powerless."
  },
  {
    "id": 70,
    "ar": "الْمُقْتَدِرُ",
    "translit": "Al-Muqtadir",
    "meaning": "The Creator of All Power",
    "category": "Power",
    "short": "The Creator of All Power.",
    "deep": "Allah's power is absolute and total, the source from which all created power and ability comes.",
    "ref": null,
    "reflection": "What outcome are you gripping tightly that isn't yours to force?",
    "action": "Release your grip on one outcome you can't control."
  },
  {
    "id": 71,
    "ar": "الْمُقَدِّمُ",
    "translit": "Al-Muqaddim",
    "meaning": "The Expediter, the Promoter",
    "category": "Power",
    "short": "The Expediter, the Promoter.",
    "deep": "Allah brings forward whoever and whatever He wills, in rank, time, or circumstance.",
    "ref": null,
    "reflection": "What have you been putting off that could move forward today?",
    "action": "Move one delayed task forward today."
  },
  {
    "id": 72,
    "ar": "الْمُؤَخِّرُ",
    "translit": "Al-Mu'akhkhir",
    "meaning": "The Delayer",
    "category": "Power",
    "short": "The Delayer.",
    "deep": "Allah delays whoever and whatever He wills, according to His perfect timing and wisdom.",
    "ref": null,
    "reflection": "What are you rushing that might need to wait?",
    "action": "Accept one delay today as wisdom, not punishment."
  },
  {
    "id": 73,
    "ar": "الأَوَّلُ",
    "translit": "Al-Awwal",
    "meaning": "The First",
    "category": "Majesty",
    "short": "The First.",
    "deep": "Allah existed before all things, with no beginning and nothing preceding Him.",
    "ref": "Surah Al-Hadid 57:3",
    "reflection": "What in your life had a beginning you didn't control?",
    "action": "Reflect that Allah existed before every beginning you know."
  },
  {
    "id": 74,
    "ar": "الآخِرُ",
    "translit": "Al-Akhir",
    "meaning": "The Last",
    "category": "Majesty",
    "short": "The Last.",
    "deep": "Allah will remain after all creation ceases to exist, with no end to His existence.",
    "ref": "Surah Al-Hadid 57:3",
    "reflection": "What are you building as if it will last forever?",
    "action": "Build one thing today with eternity, not permanence, in mind."
  },
  {
    "id": 75,
    "ar": "الظَّاهِرُ",
    "translit": "Az-Zahir",
    "meaning": "The Manifest, the Evident",
    "category": "Knowledge",
    "short": "The Manifest, the Evident.",
    "deep": "Allah's existence and signs are manifest and evident throughout all of creation.",
    "ref": "Surah Al-Hadid 57:3",
    "reflection": "What is obvious in your life that you've stopped noticing?",
    "action": "Notice one obvious sign of Allah you've been overlooking."
  },
  {
    "id": 76,
    "ar": "الْبَاطِنُ",
    "translit": "Al-Batin",
    "meaning": "The Hidden, the Unseen",
    "category": "Knowledge",
    "short": "The Hidden, the Unseen.",
    "deep": "Allah's true reality is hidden from human perception, known fully only to Himself.",
    "ref": "Surah Al-Hadid 57:3",
    "reflection": "What private matter do you carry that only Allah fully knows?",
    "action": "Keep one private matter between you and Allah alone today."
  },
  {
    "id": 77,
    "ar": "الْوَالِي",
    "translit": "Al-Wali (Al-Waali)",
    "meaning": "The Governor, the Ruler",
    "category": "Protection",
    "short": "The Governor, the Ruler.",
    "deep": "Allah governs and manages the affairs of all creation with complete authority and care.",
    "ref": null,
    "reflection": "Who or what are you letting manage your affairs today?",
    "action": "Let Allah manage one affair you've been over-managing."
  },
  {
    "id": 78,
    "ar": "الْمُتَعَالِي",
    "translit": "Al-Muta'ali",
    "meaning": "The Most Exalted",
    "category": "Majesty",
    "short": "The Most Exalted.",
    "deep": "Allah is exalted far above any flaw, need, or limitation that could ever be attributed to Him.",
    "ref": null,
    "reflection": "Where do you need to rise above a pettiness in your day?",
    "action": "Rise above one petty argument today."
  },
  {
    "id": 79,
    "ar": "الْبَرُّ",
    "translit": "Al-Barr",
    "meaning": "The Doer of Good",
    "category": "Beauty",
    "short": "The Doer of Good.",
    "deep": "Allah is the source of all true goodness, kindness, and generosity toward His creation.",
    "ref": null,
    "reflection": "What small kindness could you offer today without being asked?",
    "action": "Do one unprompted kindness today."
  },
  {
    "id": 80,
    "ar": "التَّوَّابُ",
    "translit": "At-Tawwab",
    "meaning": "The Ever-Returning, Accepter of Repentance",
    "category": "Forgiveness",
    "short": "The Ever-Returning, Accepter of Repentance.",
    "deep": "Allah continually turns toward His servants in mercy, accepting sincere repentance again and again.",
    "ref": null,
    "reflection": "What is a return you keep meaning to make, but haven't yet?",
    "action": "Make sincere tawbah for something specific today."
  },
  {
    "id": 81,
    "ar": "الْمُنْتَقِمُ",
    "translit": "Al-Muntaqim",
    "meaning": "The Avenger",
    "category": "Justice",
    "short": "The Avenger.",
    "deep": "Allah brings just retribution upon those who persist in wrongdoing after every chance to repent.",
    "ref": null,
    "reflection": "Where do you seek justice through anger instead of patience?",
    "action": "Leave one grievance to Allah instead of retaliating."
  },
  {
    "id": 82,
    "ar": "العَفُوُّ",
    "translit": "Al-Afuww",
    "meaning": "The Pardoner, the Effacer of Sins",
    "category": "Forgiveness",
    "short": "The Pardoner, the Effacer of Sins.",
    "deep": "Allah pardons and erases sins entirely for those who sincerely seek His forgiveness.",
    "ref": null,
    "reflection": "What fault of someone else could you choose to erase rather than remember?",
    "action": "Forgive one person completely today, without conditions."
  },
  {
    "id": 83,
    "ar": "الرَّؤُوفُ",
    "translit": "Ar-Ra'uf",
    "meaning": "The Most Kind, the Compassionate",
    "category": "Mercy",
    "short": "The Most Kind, the Compassionate.",
    "deep": "Allah is exceptionally kind and gentle with His servants, especially in their weakness and need.",
    "ref": null,
    "reflection": "Where do you need tenderness instead of correction?",
    "action": "Be tender with someone who's struggling today."
  },
  {
    "id": 84,
    "ar": "مَالِكُ الْمُلْكِ",
    "translit": "Malik-ul-Mulk",
    "meaning": "Owner and Sovereign of All Dominion",
    "category": "Majesty",
    "short": "Owner and Sovereign of All Dominion.",
    "deep": "Allah is the true Owner and Sovereign of all dominion, granting and removing authority as He wills.",
    "ref": null,
    "reflection": "What do you own that you're gripping too tightly?",
    "action": "Give up attachment to one possession today, even briefly."
  },
  {
    "id": 85,
    "ar": "ذُوالْجَلاَلِ وَالإكْرَامِ",
    "translit": "Dhul-Jalali wal-Ikram",
    "meaning": "Lord of Majesty and Generosity",
    "category": "Majesty",
    "short": "Lord of Majesty and Generosity.",
    "deep": "Allah combines perfect majesty with abundant generosity, deserving both awe and love.",
    "ref": null,
    "reflection": "Where do majesty and closeness meet in how you see Allah?",
    "action": "Balance awe and closeness in one dua today."
  },
  {
    "id": 86,
    "ar": "الْمُقْسِطُ",
    "translit": "Al-Muqsit",
    "meaning": "The Equitable One",
    "category": "Justice",
    "short": "The Equitable One.",
    "deep": "Allah is perfectly equitable, establishing justice and fairness in every matter without exception.",
    "ref": null,
    "reflection": "Where have you been unfair, even in something small?",
    "action": "Correct one small unfairness you've overlooked."
  },
  {
    "id": 87,
    "ar": "الْجَامِعُ",
    "translit": "Al-Jami",
    "meaning": "The Gatherer, the Uniter",
    "category": "Power",
    "short": "The Gatherer, the Uniter.",
    "deep": "Allah will gather all of creation together on the Day of Judgment, and unites what is scattered by His will.",
    "ref": null,
    "reflection": "What scattered pieces of your life need to be brought together?",
    "action": "Bring together one thing (relationship, task) that's scattered."
  },
  {
    "id": 88,
    "ar": "الْغَنِيُّ",
    "translit": "Al-Ghani",
    "meaning": "The Self-Sufficient, the Rich",
    "category": "Sustenance",
    "short": "The Self-Sufficient, the Rich.",
    "deep": "Allah is entirely self-sufficient, needing nothing from His creation while everything needs Him.",
    "ref": null,
    "reflection": "What are you chasing that you don't actually need?",
    "action": "Let go of chasing one unnecessary want today."
  },
  {
    "id": 89,
    "ar": "الْمُغْنِي",
    "translit": "Al-Mughni",
    "meaning": "The Enricher",
    "category": "Sustenance",
    "short": "The Enricher.",
    "deep": "Allah enriches whoever He wills with wealth, contentment, or sufficiency, materially or spiritually.",
    "ref": null,
    "reflection": "What need do you have today that could be met without your effort?",
    "action": "Ask Allah to enrich you in one specific way today."
  },
  {
    "id": 90,
    "ar": "اَلْمَانِعُ",
    "translit": "Al-Mani",
    "meaning": "The Preventer of Harm",
    "category": "Protection",
    "short": "The Preventer of Harm.",
    "deep": "Allah prevents harm from reaching His servants when He wills, shielding them from what would hurt them.",
    "ref": null,
    "reflection": "What harm has quietly been kept away from you unnoticed?",
    "action": "Thank Allah for one harm you never even noticed being prevented."
  },
  {
    "id": 91,
    "ar": "الضَّارُّ",
    "translit": "Ad-Darr",
    "meaning": "The One Who Ordains Harm (only by His wisdom)",
    "category": "Justice",
    "short": "The One Who Ordains Harm (only by His wisdom).",
    "deep": "Allah permits difficulty and harm to occur within His wise plan, never without reason or purpose.",
    "ref": null,
    "reflection": "How does understanding hardship as permitted, not random, change your response to it?",
    "action": "Accept one hardship today as permitted, not senseless."
  },
  {
    "id": 92,
    "ar": "النَّافِعُ",
    "translit": "An-Nafi",
    "meaning": "The Bestower of Benefit",
    "category": "Sustenance",
    "short": "The Bestower of Benefit.",
    "deep": "Allah is the source of every true benefit that reaches His creation, however it may arrive.",
    "ref": null,
    "reflection": "What benefit reached you today that you almost missed noticing?",
    "action": "Notice and thank Allah for one benefit you almost missed."
  },
  {
    "id": 93,
    "ar": "النُّورُ",
    "translit": "An-Nur",
    "meaning": "The Light",
    "category": "Guidance",
    "short": "The Light.",
    "deep": "Allah is the light of the heavens and the earth, the source of guidance, clarity, and truth.",
    "ref": "Surah An-Nur 24:35",
    "reflection": "Where do you feel lost in the dark right now?",
    "action": "Ask Allah for light in one area of confusion today."
  },
  {
    "id": 94,
    "ar": "الْهَادِي",
    "translit": "Al-Hadi",
    "meaning": "The Guide",
    "category": "Guidance",
    "short": "The Guide.",
    "deep": "Allah guides whoever He wills to the straight path, illuminating the way for sincere hearts.",
    "ref": null,
    "reflection": "What decision are you struggling to make that needs guidance?",
    "action": "Ask for guidance before one decision today."
  },
  {
    "id": 95,
    "ar": "الْبَدِيعُ",
    "translit": "Al-Badi",
    "meaning": "The Incomparable Originator",
    "category": "Creation",
    "short": "The Incomparable Originator.",
    "deep": "Allah originates creation in ways that have no precedent or equal, without any model to imitate.",
    "ref": null,
    "reflection": "What in creation strikes you as impossible to imitate?",
    "action": "Marvel at one thing in creation with no precedent to copy."
  },
  {
    "id": 96,
    "ar": "اَلْبَاقِي",
    "translit": "Al-Baqi",
    "meaning": "The Everlasting",
    "category": "Majesty",
    "short": "The Everlasting.",
    "deep": "Allah remains everlasting after all else perishes, the only reality that never ends.",
    "ref": null,
    "reflection": "What are you afraid of losing that will not actually last forever anyway?",
    "action": "Invest in one thing today that will outlast this world."
  },
  {
    "id": 97,
    "ar": "الْوَارِثُ",
    "translit": "Al-Warith",
    "meaning": "The Inheritor of All",
    "category": "Majesty",
    "short": "The Inheritor of All.",
    "deep": "Allah is the ultimate Inheritor of everything; all creation and possessions return to Him alone.",
    "ref": null,
    "reflection": "What will remain of your actions after everything else is gone?",
    "action": "Do one deed today meant to outlive you."
  },
  {
    "id": 98,
    "ar": "الرَّشِيدُ",
    "translit": "Ar-Rashid",
    "meaning": "The Guide to the Right Path",
    "category": "Guidance",
    "short": "The Guide to the Right Path.",
    "deep": "Allah guides His creation with perfect wisdom toward what truly benefits them.",
    "ref": null,
    "reflection": "Whose advice do you trust, and does it lead toward what's right?",
    "action": "Seek out advice from someone trustworthy today."
  },
  {
    "id": 99,
    "ar": "الصَّبُورُ",
    "translit": "As-Sabur",
    "meaning": "The Most Patient",
    "category": "Patience",
    "short": "The Most Patient.",
    "deep": "Allah is patient with His servants, delaying consequence and giving ample opportunity to return to Him.",
    "ref": null,
    "reflection": "What are you waiting on right now that tests your patience?",
    "action": "Wait on one matter today without forcing an outcome."
  }
];